export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FILTER_PRODUCTS_BY_SIZES = "FILTER_PRODUCTS_BY_SIZES";
export const ORDER_PRODUCTS_BY_PRICES = "ORDER_PRODUCTS_BY_PRICES";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";

export const FETCH_ORDERS_BY_EMAIL = "FETCH_ORDERS_BY_EMAIL"
export const FETCH_ORDERS_BY_EMAIL_FAILURE = "FETCH_ORDERS_BY_EMAIL_FAILURE"

export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE";

export const SIGN_UP_WITH_EMAIL_AND_PASSWORD = "SIGN_UP_WITH_EMAIL_AND_PASSWORD";
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD_FAILURE = "SIGN_UP_WITH_EMAIL_AND_PASSWORD_FAILURE";

export const SIGN_IN_WITH_EMAIL_AND_PASSWORD = "SIGN_IN_WITH_EMAIL_AND_PASSWORD";
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILURE = "SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILURE";

export const SIGN_OUT = "SIGN_OUT";
export const AUTH_STATE_CHANGE = "AUTH_STATE_CHANGE"


